---
- name: Deploy Nginx Docker Container
  hosts: servers
  become: true
  vars:
    repo_url: "https://github.com/devops-donm/nginx_container.git"
    repo_path: "/opt/nginx_container"
  tasks:

    # Step 2: Download the GitHub repository
    - name: Clone the GitHub repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_path }}"
        version: main  # Specify branch if needed
        force: yes  # Force re-download if repo already exists

    # Step 3: Stop and remove any existing container
    - name: Stop existing Docker containers
      ansible.builtin.command:
        cmd: docker-compose down
        chdir: "{{ repo_path }}"
      ignore_errors: true  # Ignore errors if container is not running

    # Step 4: Create a new Docker container
    - name: Build and start new Docker containers
      ansible.builtin.command:
        cmd: docker-compose up -d --build
        chdir: "{{ repo_path }}"
